# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:

    encoders:
        AppBundle\Entity\User:
            algorithm: bcrypt
            cost: 12


    # http://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        our_db_provider:
            entity:
                class: AppBundle:User
                property: username


    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern:    ^/
            http_basic: ~
            provider: our_db_provider
            anonymous: ~
            #oauth:
            #    resource_owners:
            #    google:             "/oauth-login/check-google"
            #    login_path:        /oauth-login
            #    use_forward:       false
            #    failure_path:      /oauth-login

            #   oauth_user_provider:
            #        service: hwi_oauth.user.provider

            form_login:
                login_path: app.security.login
                check_path: app.security.login
                default_target_path: app.admin.index
            logout:
                path:   app.security.logout
                target: app.homepage.index
                invalidate_session: false

            # activate different ways to authenticate

            # http_basic: ~
            # http://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: ~
            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html
    access_control:
        - { path: /admin, roles: ROLE_ADMIN }
        - { path: /order, roles: ROLE_USER }
        - { path: /oauth-login, roles: IS_AUTHENTICATED_ANONYMOUSLY }

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER