<?php
/**
 * Created by PhpStorm.
 * User: jeremie
 * Date: 19/03/17
 * Time: 11:06
 */

namespace AppBundle\Service\Utils;


use AppBundle\Entity\User;
use AppBundle\Entity\XmlRecord;
use Symfony\Bundle\FrameworkBundle\Test\KernelTestCase;
use Symfony\Component\Config\Util\XmlUtils;

class MailUtilsTest extends KernelTestCase
{

    static protected $container;

    /** @var  MailUtils $mail */
    static protected $mail;
    static protected $rootDir;

    public static function setUpBeforeClass()
    {
        $kernel = static::createKernel();
        $kernel->boot();

        self::$rootDir = $kernel->getRootDir();

        //get the DI container
        self::$container = $kernel->getContainer();
        self::$mail = self::$container->get('app.services.utils.mail');
        parent::setUpBeforeClass(); // TODO: Change the autogenerated stub
    }

    public function testProcessFileMockStandard()
    {
        //Registry $doctrine, XmlRecordUtils $xmlRecordUtils

        $mockUser = $this->createMock(User::class);
        $mockUser->expects($this->once())
            ->method('getUsername')
            ->will($this->returnValue("username@gmail.com"));

        $mockXmlRecord = $this->createMock(XmlRecord::class);
        $mockXmlRecord->expects($this->once())
            ->method('getClientEmail')
            ->will($this->returnValue("gegeturambar@gmail.com"));

        $path = self::$rootDir . "/Resources/views/Emails/standard.html.twig";
        $path = "Emails/standard.html.twig";
        $ret = self::$mail->SendMail($mockXmlRecord, $mockUser, $path);
        $this->assertEquals(count($ret), 1);
    }
}
